export { UserClass } from './user.interface'
export { AuthClass } from './auth.interface'
export { BeatsClass } from './beat.interface'
export { GenreClass } from './genre.interface'
export { ReviewsClass } from './review.interface'
